export const INIT = 'INIT'
export const LOADING = 'LOADING'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const ERROR = 'ERROR'
export const CHANGE_FORM_INPUT = 'CHANGE_FORM_INPUT'
export const RESET = 'RESET'